blog/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('article_detail/<int:pk>/', views.article_detail, name='article_detail'),
    # api urls
    path('articles/', views.article_list_api),
    path('articles/<int:pk>/', views.article_detail_api),
] 
urlpatterns = format_suffix_patterns(urlpatterns)

wmcode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# api imports


class Author(models.Model):
	name = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.name


	class Meta:
		db_table = 'author'

class Article(models.Model):
	title = models.CharField(max_length=200, blank=True, null=True)
	author = models.ForeignKey('Author', max_length=200, blank=True, null=True, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	sub_heading_1 = models.CharField(max_length=200, blank=True, null=True)
	body_one = models.TextField(blank=True, null=True)
	img_one = models.FileField(upload_to='uploads/', blank=True, null=True)
	sub_heading_2 = models.CharField(max_length=200, blank=True, null=True)
	code_one = models.TextField(blank=True, null=True)
	body_two = models.TextField(blank=True, null=True)

	sub_heading_3 = models.CharField(max_length=200, blank=True, null=True)
	body_three = models.TextField(blank=True, null=True)
	img_two = models.FileField(upload_to='uploads/', blank=True, null=True)
	sub_heading_4 = models.CharField(max_length=200, blank=True, null=True)
	code_two = models.TextField(blank=True, null=True)
	body_four = models.TextField(blank=True, null=True)

	sub_heading_5 = models.CharField(max_length=200, blank=True, null=True)
	body_five = models.TextField(blank=True, null=True)
	img_three = models.FileField(upload_to='uploads/', blank=True, null=True)
	sub_heading_6 = models.CharField(max_length=200, blank=True, null=True)
	code_three = models.TextField(blank=True, null=True)
	body_six = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.title

	class Meta:
		db_table = 'article'

class Comments(models.Model):
	article =  models.ForeignKey('Article', on_delete=models.CASCADE, blank=True, null=True)
	comment_body = models.TextField(blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	comment_owner = models.ForeignKey('Comment_owner', on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		return self.comment_body


	class Meta:
		db_table = 'comments'

class Comment_owner(models.Model):
	name = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.name


	class Meta:
		db_table = 'comment_owner'
			

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    your_name = forms.CharField(label='Name', max_length=200)
    message = forms.CharField(widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from . models import Article, Comments, Comment_owner, Author
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from . serializers import ArticleSerializer
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

def index(request):
	articles = Article.objects.all()
	return render(request, 'blog/index.html', {'articles':articles})

def article_detail(request, pk):
	detailed_article = get_object_or_404(Article, pk=pk)
	return render(request, 'blog/article_detail.html', {'detailed_article':detailed_article})


@api_view(['GET', 'POST'])
def article_list_api(request, format=None):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        article_list = Article.objects.all()
        serializer = ArticleSerializer(article_list, many=True)
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ArticleSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


@api_view(['GET', 'PUT', 'DELETE'])
def article_detail_api(request, pk, format=None):
    """
    Retrieve, update or delete a code snippet.
    """
    # try:
    #     article = Article.objects.get(pk=pk)
    # except Article.DoesNotExist:
    #     return HttpResponse(status=404)
    article = get_object_or_404(Article, pk=pk)

    if request.method == 'GET':
        serializer = ArticleSerializer(article)
        return JsonResponse(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = ArticleSerializer(article, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        article.delete()
        return HttpResponse(status=204)

blog/templates/blog/about.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="static/css/article_detail.css">
	<link rel="stylesheet" href="static/css/styles/default.css">
	<script type="text/javascript" src="static/js/index.js"></script>
    <script src="static/js/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
		<header>
		<div class="header-menu-one">
			<span class="logo">W.M<span>Code</span></span>
			<span class="home"><a href="index.html">Home</a></span>
			<span class="about">About</span>
			<span class="projects">Projects</span>
			<span class="contact">Contact</span>
		</div>
	</header>

	<section class="about-ection-main">
		<div>
			<span class="about-me-text">About Me</span><br>
			<img class="profile-pic" src="static/images/thumbnails/4rsmokehouse.com-crop.png"></div>
		<p>
			I you are on this page that means you are wondering who am I. The simple version, I am just a guy who loves to code, 'Yes I do love to code'. <br>
		</p>

		<p>
			Prior to june 2017 I had no idea what computer programming was all about. I would always get amazed each time I look at a computer and see what it can do. I had no clue that the heart of all software on my computer was computer programming. <br>
		</p>

        <p>
			One day a friend mensioned the dreaded statement, "computer programming", in my presence. Wondering what that was all about I found myself on all all time friend google, googling 'computer programming'. Then google bombaded me with lots of jibrish that I could not understand, little did I know that was actually programming language sytaxes. <br>
		</p>

		<p>
			I downloaded a C# texbook , tried to devulge myself in it, few minutes later , I found myself taking cafenols trying to alleviate a deadache, " I blammed c# for that". <br>
		</p>

        <p>
			Latter that week as I become more weary about computer proggramming , I saw a coding advert from a local hub. I applied, made all the necessary arrangements. A month later , I found myself seating on a computer strugling to understand basics python on Treehouse as it turns out the hub was a afiliate of treehouse which was all good. I loved Treehouse.<br>
		</p>

		<p>
			From python basics to advance Object oriented , flask, django. I started playing around with these building some prototype sites, The sites were not impressive though. Something was lack. After some time I started doing HTML and CSS. With a markup language and cascading style sheets on my belt , my sites begin look better. 
			<br>
		</p>

		<p>
			Fast forward 2019 I joined the php bendwagon. Played a little with wordpress. I did some unspeakable things to wordpress themes. Well I was learning. <br>
		</p>

		<p>
			I realised I am not immune to frustration , demotivation from spending hundreds of hours stering at a computer screen trying to debug some code. So created <span class="logo">W.M<span>Code</span></span> to help me minimise the frustration and demotivation by documenting my learning activities.
		</p>

			<h5>Honestly I am still learning, so they are definately going to be lots of bugs in my small projects</h5>


			<b>Thank you for vising my blog</b><br><br>

			<span>Check out my contacts page for my contacts <a href="contacts.html">contact information</a></span>


		<div>
			<span>Technologies used to build this blog</span><br>
			<ul>
				<li><h4>FrontEnd</h4></li>
				<li>HTML</li>
				<li>CSS</li>
				<li>Javascript</li>
				<li><h4>BackEnd</h4></li>
				<li>php</li>
			</ul>
			<span>No frameworks are used for learnig purposes</span>
		</div>
	</section>





	<!-- Footer Start -->
	
    <footer>W.M Code &copy; 2019</footer>
	<!-- Footer End -->
</body>
</html>

blog/templates/blog/article_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/styles/default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/article_detail.css' %}">
	<script type="text/javascript" src="{% static 'blog/js/index.js' %}"></script>
	<script type="text/javascript" src="{% static 'blog/js/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
	<header>
		<div class="header-menu-one">
			<span class="logo">W.M<span>Code</span></span>
			<span class="home"><a href="{% url 'blog:index' %}">Home</a></span>
			<span class="about">About</span>
			<span class="projects">Projects</span>
			<span class="contact">Contact</span>
		</div>
	</header>

    <!-- Section-C start -->
    <!-- first part of page start -->
    <section class="sectionC">
    	{% if detailed_article.title %}
    	<div class="sectionC-title">
    		{{detailed_article.title}}	
    	</div>
    	{% endif %}

    	{% if detailed_article.sub_heading_1 %}
    	<div class="sectionC-title">	
    		{{detailed_article.sub_heading_1}}	
    	</div>
    	{% endif %}

        {% if detailed_article.body_one %}
	    <div>	
    		{{detailed_article.body_one}}	
	    </div>
	    {% endif %}
 
        {% if detailed_article.img_one %}
	    <div>	 
    		<img src="{{detailed_article.img_one.url}}">	
	    </div>
	    {% endif %}

	     {% if detailed_article.body_two %}
	    <div>	
    		{{detailed_article.body_two}}	
	    </div>
	    {% endif %}

	    <!-- --------------------new part page -->
	    <!-- ==================================== -->


	    {% if detailed_article.sub_heading_2 %}
    	<div class="sectionC-title">	
    		{{detailed_article.sub_heading_2}}	
    	</div>
    	{% endif %}

        {% if detailed_article.code_one %}
	    <div>
	    	<div>
	    		<pre>
				    <code>
			    		{{detailed_article.code_one}}
					</code>
				</pre>	
	        </div>
	    </div>
	    {% endif %}


	    <!--. -->
	    {% if detailed_article.body_three %}
	    <div>	
    		{{detailed_article.body_three}}	
	    </div>
	    {% endif %}

	    {% if detailed_article.img_two %}
	    <div>	 
    		<img src="{{detailed_article.img_two.url}}">	
	    </div>
	    {% endif %}

	    {% if detailed_article.body_four %}
	    <div>	
    		{{detailed_article.body_four}}	
	    </div>
	    {% endif %}

	    <!-- ----------------------------------------- -->
	    <!-- ========================================= -->
	    {% if detailed_article.sub_heading_3 %}
    	<div class="sectionC-title">	
    		{{detailed_article.sub_heading_3}}	
    	</div>
    	{% endif %}
        
        {% if detailed_article.code_two %}
	    <div>
	    	<div>
	    		<pre>
				    <code class="css">
			    		{{detailed_article.code_two}}	
					</code>
				</pre>	
	        </div>
	    </div>
	    {% endif %}


	    <!--. -->
	    {% if detailed_article.body_five %}
	    <div>	
    		{{detailed_article.body_five}}	
	    </div>
	    {% endif %}

	    {% if detailed_article.img_three %}
	    <div>	 
    		<img src="{{detailed_article.img_three.url}}">	
	    </div>
	    {% endif %}

	    {% if detailed_article.body_six %}
	    <div>	
    		{{detailed_article.body_six}}	
	    </div>
	    {% endif %}

	    <!-- ----------------------------------------- -->
	    <!-- ========================================= -->

	   


	    <div class="comment_form">
	    	<p>Feel free to comment below</p>
	    	<form>
	    		<div>Name</div>
	    		<input class="name" type="text" name="name"><br>
	    		<div>Comment</div>
	    		<textarea name="comment_message">
	    			
	    		</textarea><br>
	    		<input class="submit" type="submit" name="submit comment">
	    	</form>
	    </div>
	    <hr>
	    <div>All coments <span>{{detailed_article.comments_set.all|length}}</span></div>


<!-- example comment without replies -->
<!-- 	    <div class="comment_text_container">
	    	<span class="comment_owner">Wisdom</span><br>
	    	<span class="comment">This is my comment</span><br> 
	    </div>
 -->
        {% for comment in detailed_article.comments_set.all %}
	    <div class="comment_text_container">
	    	<span class="comment_owner">{{comment.comment_owner.name}}</span><br>
	    	<span class="comment">{{comment.comment_body}}</span><br> 
	    </div>
        {% endfor %}
	</section>

    <!-- Section-C end -->
    <!-- --------------------------------------------------- -->




	<!-- Footer Start -->


    <footer>W.M Code &copy; 2019</footer>
	<!-- Footer End -->
</body>
</html>

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/index.css' %}">
	<script type="text/javascript" src="{% static 'blog/js/index.js' %}"></script>
</head>
<body>

	<header>
		<div class="header-menu-one">
			<span class="logo">W.M<span>Code</span></span>
			<span class="home">Home</span>
			<span class="about">About</span>
			<span class="projects">Projects</span>
			<span class="contact">Contact</span>
		</div>
		<div class="header-menu-two">
			<div class="header-menu-two-divone">
				<p style="font-size: 25px;">W.M Code</p>
				<p style="font-size: 13px;">This is a site for  coding. That's all.  Enjoy! </p>
			</div>
			<div class="header-menu-two-divtwo">
				<p style="font-size: 25px;">Favourite quote</p>
				<p style="font-size: 13px;"><i>Computer programming is an art, because it applies accumulated knowledge to the world, because it requires skill and ingenuity, and especially because it produces objects of beauty. A programmer who subconsciously views himself as an artist will enjoy what he does and will do it better.</i>
					<br>
					<br>
					<br>
				<i>Donald Knuth</i></p>
			</div>
		</div>
	</header>

	<!-- Section A starts -->
	{% for article in articles %}
	<section class="sectionA">
		<div class="sectionA-title">
			{{article.title}}
		</div>
		<div>
			{% if article.img_one %}
			<img class="sectionA-img" src="{{ article.img_one.url}}">
			{% endif %}
		</div>
		<div>
			{{article.body_one}}
		</div>
		<div class="sectionA-read-more"><a href="{% url 'blog:article_detail' article.id %}">Read More</a></div>
		<div class="sectionA-last-div">
			<span>Published: {{article.pub_date}}</span>
			<span>Author: {{article.author.name}}</span>
			<span>Comments {{article.comments_set.all|length}}</span>
		</div>
	</section>
	{% endfor %}
	<!-- Section A ends -->
	<!-- ------------------------------------------------------------- -->
	<!-- Section B starts -->
	<!-- <section class="sectionB">
		<div class="sectionB-title">Building a Home page part one</div>
		<div>
			<img class="sectionB-img" src="static/images/thumbnails/httpswww.freshbooks-crop.com.png">
		</div>
		<div>Computer programming is an art, because it applies accumulated knowledge to the world, because it requires skill and ingenuity, and especially because it produces objects of beauty. A programmer who subconsciously views himself as an artist will enjoy what he does and will do it better.
		Donald KnuthComputer programming is an art, because it applies accumulated knowledge to the world, because it requires skill and ingenuity, and especially because it produces objects of beauty. A programmer who subconsciously views himself as an artist will enjoy what he does and will do it better.
		Donald Knuth</div>
		<div class="sectionB-read-more">Read More</div>
		<div class="sectionB-last-div">
			<span>Published: 2 june</span>
			<span>Author: w.m code</span>
			<span>Comments 300</span>
		</div>
	</section> -->
	<!-- Section B ends -->

	<!-- Footer Start -->
	<div class="more-projects">WORKING ON MORE PROJECTS. CHECK BACK FEW WEEKS FROM NOW</div>

    <footer>W.M Code &copy; 2019</footer>
	<!-- Footer End -->
</body>
</html>